### ISSUE TITLE
 WARNING Proof of work too weak for block 400149 (0ea15d07738055e45ed633fa37646c4a91076a178b40963b85b9613c063806d9)

### ISSUE THREAD

**Issue by pitilesspoppies** [NinjaCoin-Master/NinjaCoin#2]
This error occurred while I was synchronizing blocks:
WARNING Proof of work too weak for block 400149 (0ea15d07738055e45ed633fa37646c4a91076a178b40963b85b9613c063806d9)
Now, the wallet has been unable to complete synchronization, how to deal with it?

**Comment by NinjaCoin-Master** [comment]
Fixed, download the new release, and rescan the blockchain! Thank you @pitilesspoppies
