### ISSUE TITLE
Copyright & License Violation

### ISSUE THREAD

**Issue by brandonlehmann** [NinjaCoin-Master/NinjaCoin#4]
You have performed a massive Find & Replace for the word "TurtleCoin" in your obviously forked project to "NinjaCoin" including purposefully removing the link to the LicenseCanary header to disable that check and allow the software to compile despite your disregard for the License requirements. Please rectify this issue immediately.

**Comment by NinjaCoin-Master** [comment]
I will correct soon, thanks!

**Comment by brandonlehmann** [comment]
It would be wise to keep this issue open until it's actually corrected.
